# Generated by Django 3.0.14 on 2021-06-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landinpage', '0002_secteur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Secteur',
            new_name='Sector',
        ),
    ]
