# Generated by Django 3.0.14 on 2021-06-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landinpage', '0003_auto_20210604_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
