# Generated by Django 3.0.14 on 2021-06-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landinpage', '0004_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
