# Generated by Django 3.0.14 on 2021-06-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landinpage', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
