# Generated by Django 3.0.14 on 2021-06-11 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landinpage', '0007_auto_20210609_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.ImageField(upload_to='projects'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('fonction', models.CharField(max_length=200)),
                ('team_img', models.ImageField(upload_to='team')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='landinpage.Sector')),
            ],
        ),
    ]
