# Generated by Django 3.0.14 on 2021-06-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landinpage', '0008_auto_20210611_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=150)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
